# Generated by Django 2.1.15 on 2020-11-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formularioRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=255)),
                ('Rut', models.CharField(max_length=255)),
                ('Nombres', models.CharField(max_length=255)),
                ('Apellidos', models.CharField(max_length=255)),
                ('Dia', models.CharField(max_length=2)),
                ('Mes', models.CharField(max_length=2)),
                ('Anno', models.CharField(max_length=2)),
                ('Telefono', models.CharField(max_length=9)),
                ('Region', models.CharField(max_length=255)),
                ('Comuna', models.CharField(max_length=255)),
                ('TipoViaje', models.CharField(max_length=255)),
            ],
        ),
    ]
