# Generated by Django 2.1.15 on 2020-11-09 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioregistro',
            name='Comuna',
        ),
        migrations.RemoveField(
            model_name='formularioregistro',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='formularioregistro',
            name='TipoViaje',
        ),
    ]
