# Generated by Django 2.1.15 on 2020-11-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201109_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioregistro',
            name='Anno',
        ),
        migrations.RemoveField(
            model_name='formularioregistro',
            name='Dia',
        ),
        migrations.RemoveField(
            model_name='formularioregistro',
            name='Mes',
        ),
    ]
