# Generated by Django 2.1.15 on 2020-11-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201109_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioregistro',
            name='Comuna',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='formularioregistro',
            name='Region',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='formularioregistro',
            name='TipoViaje',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='formularioregistro',
            name='Rut',
            field=models.CharField(max_length=10),
        ),
    ]
