# Generated by Django 2.1.15 on 2020-11-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagen',
        ),
        migrations.AddField(
            model_name='formularioregistro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Viajes'),
        ),
    ]
