# Generated by Django 2.1.15 on 2020-11-10 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201109_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formularioregistro',
            old_name='imagen',
            new_name='Imagen',
        ),
    ]
