# Generated by Django 2.1.15 on 2020-11-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201110_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='subirImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='Viajes')),
            ],
        ),
        migrations.RemoveField(
            model_name='formularioregistro',
            name='Imagen',
        ),
    ]
