# Generated by Django 2.1.15 on 2020-11-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201110_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subirImagen',
        ),
        migrations.AddField(
            model_name='formularioregistro',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='Viajes'),
        ),
    ]
